services:
  - type: web
    name: arjan-ai-server-backend
    env: node
    buildCommand: npm install
    startCommand: node api/chat.js
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MODEL_NAME
        sync: false
