services:
  - type: web
    name: arjan-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20.x
